### PR TITLE
Cache fresh responses even if they have 'must-revalidate'

### PR DESCRIPTION
**Pull request by jstastny**
My take on #100.

This may be naive and/or missing something, but I wanted to open the discussion with this PR.

### CODE REVIEW

**Comment by jstastny** [comment]
@lucasmazza -- could you, please, take a look at this PR and possibly merge it? Thanks!

**Comment by lucasmazza** [comment]
@jstastny I'll take a look on this (and do my periodic re-read of the RFC 🏃 ) on the next few days

**Comment by jstastny** [comment]
@lucasmazza -- any update on this? It would be great to see this merged so we can stop using our fork. Thanks!

**Comment by jstastny** [comment]
@lucasmazza -- any chance you could take a look at this some time soon?

**Comment by jstastny** [comment]
@lucasmazza -- sorry to bother, but any chance you would look into this? I would love to stop using our fork of this. Thanks!

**Comment by lucasmazza** [comment]
@jstastny thanks for the patch and the year long patience 🙏

**Comment by gradybarrett** [comment]
Any chance of a new version getting released soon that includes this?

**Pull request merged**
